-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('ORDER_UPDATE', 'PRODUCT_STATUS', 'VENDOR_APPROVAL', 'VENDOR_REGISTRATION', 'ADMIN_ALERT', 'GENERAL', 'ADD_PRODUCT', 'LOW_STOCK', 'ORDER_SHIPPED', 'VENDOR_REJECTED', 'MESSAGE_FROM_VENDOR', 'SUBMIT_TICKET', 'UPDATE_PRODUCT_STOCK', 'ORDER_STATUS') NOT NULL;
