-- AlterTable
ALTER TABLE `Payment` ADD COLUMN `accountNo` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `bankName` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `ifsc` VARCHAR(191) NULL DEFAULT '',
    ADD COLUMN `mode` ENUM('COD', 'BANK', 'UPI') NOT NULL DEFAULT 'COD',
    ADD COLUMN `transactionId` VARCHAR(191) NULL DEFAULT '',
    MODIFY `amount` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `method` VARCHAR(191) NOT NULL DEFAULT 'Unknown';
